# Generated by Django 5.2.3 on 2025-08-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('occupation', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('marriage', 'Marriage'), ('birthday', 'Birthday'), ('baby_shower', 'Baby Shower'), ('anniversary', 'Anniversary'), ('housewarming', 'Housewarming'), ('graduation', 'Graduation'), ('engagement', 'Engagement'), ('religious', 'Religious Ceremony')], max_length=20)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
